name: Mixed Workflow
on:
  push:
    branches: [main, develop]
  
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter message'  
        default: 'hello'   
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Message
        run: |
          echo "Hello World from scheduled GitHub Actions" 

      - name: Print Input Message
        run: |
          echo "Input: ${{ inputs.message }}" 
          
