name: Receiver 1
 
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter docker image tag'  
        default: 'v1.0.1'   
        required: true
  repository_dispatch:
    types: [build-dispatch-1]

env:
  tag: ${{ github.event_name == 'repository_dispatch' && 'v1.0.1' || inputs.tag }}

jobs:
  receiver1:
    if: ${{ github.event.client_payload.deploy == 'true' }} 
    name: Receive1
    runs-on: ubuntu-latest
    steps:
      - name: Event1 Received
        run: |
          echo "Env Var Set by repository_dispatch ${{ env.tag }}"
          echo "Payload Deploy ${{ github.event.client_payload.deploy }}"
          echo "Payload Foo '${{ github.event.client_payload.foo }}'"
