name: Receiver
 
on:
  repository_dispatch:
    types: [build-dispatch]
 
jobs:
  receiver:
    name: Receive
    runs-on: ubuntu-latest
    steps:
      - name: Event Received
        run: |
          echo ${{ github.ref_name }}
          echo "payload Foo '${{ github.event.client_payload.foo }}'"