name: Recieve Re-usable Workflow
on:
  workflow_dispatch:
  
  workflow_call:
    inputs:
      commit_id:
        required: true
        type: string

jobs:
  recieve:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print received commit_id from Dispatcher Re-usable Workflow
        run: |
            echo "${{ inputs.commit_id }}"
