name: Receiver 1
 
on:
  repository_dispatch:
    types: [build-dispatch-1]

jobs:
  receiver1:
    if: ${{ github.event.client_payload.deploy }} == 'true'
    name: Receive1
    runs-on: ubuntu-latest
    steps:
      - name: Event1 Received
        run: |
          echo "Payload Foo '${{ github.event.client_payload.foo }}'"
