name: Receiver
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'  
        type: choice
        default: "dev"  
        required: true
        options:
            - "dev"
            - "uat"
            - "prd"
  repository_dispatch:
    types: [build-dispatch]

env:    
  environment: ${{ github.event_name == 'build-dispatch' && 'dev' || inputs.environment }}

jobs:
  receiver:
    name: Receive
    runs-on: ubuntu-latest
    steps:
      - name: Event Received
        run: |
          echo ${{ github.event.inputs.environment }}
          echo ${{ github.event.client_payload.env }}
          echo "payload Foo '${{ github.event.client_payload.foo }}'"
