name: Recieve Re-usable Workflow
on:
  workflow_dispatch:
    inputs:
      commit_id:
        required: true
        type: string
  
  workflow_call:
    inputs:
      commit_id:
        required: true
        type: string
env:
  commit_id: ${{ inputs.commit_id }}
  
jobs:
  recieve:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print received commit_id from Dispatcher Re-usable Workflow
        run: |
            echo "${{ env.commit_id }}"
